<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            // Product 1
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'Google Pixel 7 Pro',
                'slug' => 'google-pixel-7-pro',
                'description' => 'The Pixel 7 Pro boasts a 50 MP main camera, a 6.7-inch OLED display, and the Google Tensor G2 chip for a seamless experience.',
                'short_description' => 'Google\'s flagship phone with top-tier camera and performance.',
                'sku' => 'GPP7-002',
                'price' => 899.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 100,
                'min_quantity' => 1,
                'weight' => 0.21,
                'dimensions' => '163.9 x 75.8 x 8.9 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51vze-OaFRL._SY679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/518xkXFOS+L._SY679_.jpg", "https://m.media-amazon.com/images/I/3142aWarw7L._SY679_.jpg", "https://m.media-amazon.com/images/I/41SBKIQvZcL._SY679_.jpg"]',
                'meta_title' => 'Google Pixel 7 Pro - 50 MP Camera',
                'meta_description' => 'Get the Google Pixel 7 Pro for unmatched camera quality and performance.',
                'rating_average' => 4.7,
                'rating_count' => 850,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 2
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'OnePlus 11',
                'slug' => 'oneplus-11',
                'description' => 'OnePlus 11 offers a 50 MP camera system, 6.7-inch AMOLED display, and Snapdragon 8 Gen 2 processor at an affordable price.',
                'short_description' => 'Affordable flagship with Snapdragon 8 Gen 2 processor and 50 MP camera.',
                'sku' => 'OP11-003',
                'price' => 749.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 200,
                'min_quantity' => 1,
                'weight' => 0.21,
                'dimensions' => '163.1 x 74.1 x 8.5 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/81fRAoUL-fL._AC_SX679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51Yui+D9NfL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71kYfbZj3ML._AC_SX679_.jpg"]',
                'meta_title' => 'OnePlus 11 - Affordable Flagship',
                'meta_description' => 'The OnePlus 11 brings flagship features with an affordable price tag.',
                'rating_average' => 4.5,
                'rating_count' => 640,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 3
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'Xiaomi 13 Pro',
                'slug' => 'xiaomi-13-pro',
                'description' => 'Xiaomi 13 Pro offers a 50 MP camera with Leica optics, Snapdragon 8 Gen 2, and a 6.73-inch AMOLED display.',
                'short_description' => 'Leica optics, Snapdragon 8 Gen 2, and stunning AMOLED display.',
                'sku' => 'X13P-004',
                'price' => 899.00,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 120,
                'min_quantity' => 1,
                'weight' => 0.23,
                'dimensions' => '162.9 x 74.6 x 8.6 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61RvCwjI7dL._SX679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61qpVPvghML._SX679_.jpg", "https://m.media-amazon.com/images/I/61jnXvSPXDL._SX679_.jpg"]',
                'meta_title' => 'Xiaomi 13 Pro - Leica Camera',
                'meta_description' => 'Xiaomi 13 Pro with Leica optics and Snapdragon 8 Gen 2 for professional photography.',
                'rating_average' => 4.6,
                'rating_count' => 720,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 4
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'Motorola Edge 40',
                'slug' => 'motorola-edge-40',
                'description' => 'Motorola Edge 40 offers a 50 MP camera, 6.55-inch OLED display, and Snapdragon 870 processor at an affordable price.',
                'short_description' => 'Affordable smartphone with solid performance and a 50 MP camera.',
                'sku' => 'ME40-005',
                'price' => 499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 0.17,
                'dimensions' => '159.9 x 74.3 x 7.6 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51k0c6YBLTL._AC_SX679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/41ihyf1p92L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/41RnMvDotYL._AC_SX679_.jpg"]',
                'meta_title' => 'Motorola Edge 40 - Budget-Friendly Smartphone',
                'meta_description' => 'The Motorola Edge 40 offers great performance at a budget price with a 50 MP camera.',
                'rating_average' => 4.3,
                'rating_count' => 510,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 5
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'Samsung Galaxy Z Fold 5',
                'slug' => 'samsung-galaxy-z-fold-5',
                'description' => 'Samsung\'s Z Fold 5 features a foldable 7.6-inch Dynamic AMOLED display, Snapdragon 8 Gen 2, and a 50 MP camera.',
                'short_description' => 'Foldable smartphone with a massive 7.6-inch display.',
                'sku' => 'SGSZ5-006',
                'price' => 1799.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 50,
                'min_quantity' => 1,
                'weight' => 0.26,
                'dimensions' => '154.9 x 67.1 x 13.4 mm (folded)',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61f3V3m9xnL._AC_SX679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61sQ6wi9SmL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71MFE2UY6-L.__AC_SX300_SY300_QL70_FMwebp_.jpg"]',
                'meta_title' => 'Samsung Galaxy Z Fold 5 - Foldable Innovation',
                'meta_description' => 'Experience the future of smartphones with the Samsung Galaxy Z Fold 5\'s foldable display.',
                'rating_average' => 4.9,
                'rating_count' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],

              // Product 6
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'Realme GT 2 Pro',
                'slug' => 'realme-gt-2-pro',
                'description' => 'Realme GT 2 Pro offers a 50 MP main camera, Snapdragon 8 Gen 1, and a 6.7-inch AMOLED display.',
                'short_description' => 'Powerful smartphone with Snapdragon 8 Gen 1 and a 50 MP camera.',
                'sku' => 'RG2P-007',
                'price' => 749.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 160,
                'min_quantity' => 1,
                'weight' => 0.20,
                'dimensions' => '164.3 x 75.6 x 8.2 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://i.ebayimg.com/images/g/egUAAOSw5wFicV3l/s-l960.webp',
                'gallery' => '["https://i.ebayimg.com/imagaqzes/g/9yMAAOSweF9it7nD/s-l960.webp", "https://i.ebayimg.com/images/g/QpIAAOSwxZ1h6nNn/s-l960.webp"]',
                'meta_title' => 'Realme GT 2 Pro - Flagship Performance',
                'meta_description' => 'The Realme GT 2 Pro offers flagship performance and an excellent 50 MP camera.',
                'rating_average' => 4.6,
                'rating_count' => 640,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 7
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'Oppo Find X5 Pro',
                'slug' => 'oppo-find-x5-pro',
                'description' => 'Oppo Find X5 Pro features a 50 MP camera, 6.7-inch OLED display, and Snapdragon 8 Gen 1.',
                'short_description' => 'Oppo\'s flagship phone with a 50 MP camera and stunning display.',
                'sku' => 'OFX5P-008',
                'price' => 1049.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 110,
                'min_quantity' => 1,
                'weight' => 0.22,
                'dimensions' => '163.7 x 73.9 x 8.5 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/71NAtIVDCKL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71m-RQssSyL._AC_SX679_.jpg", "chromewebstore.google.com/category/themes/dark"]',
                'meta_title' => 'Oppo Find X5 Pro - Premium Smartphone',
                'meta_description' => 'Oppo Find X5 Pro offers premium features with a 50 MP camera and Snapdragon 8 Gen 1 processor.',
                'rating_average' => 4.7,
                'rating_count' => 830,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 8
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'Vivo X90 Pro',
                'slug' => 'vivo-x90-pro',
                'description' => 'Vivo X90 Pro is equipped with a 50 MP main camera, Snapdragon 8 Gen 2, and a 6.78-inch AMOLED display.',
                'short_description' => 'Vivo X90 Pro offers incredible camera performance and flagship-level specifications.',
                'sku' => 'VX90P-009',
                'price' => 999.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 130,
                'min_quantity' => 1,
                'weight' => 0.21,
                'dimensions' => '164.6 x 75.2 x 9.3 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/518RsOS8u4L.__AC_SY300_SX300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61riGCTdTuL._AC_SX569_.jpg", "https://m.media-amazon.com/images/I/712d-MPlFVL._AC_SX569_.jpg"]',
                'meta_title' => 'Vivo X90 Pro - Pro-Grade Camera',
                'meta_description' => 'The Vivo X90 Pro features pro-grade camera technology and an AMOLED display.',
                'rating_average' => 4.6,
                'rating_count' => 720,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 9
            [
                'category_id' => 6,
                'subcategory_id' => 5,
                'name' => 'Sony Xperia 1 IV',
                'slug' => 'sony-xperia-1-iv',
                'description' => 'Sony Xperia 1 IV offers a 12 MP camera system, a 6.5-inch 4K OLED display, and Snapdragon 8 Gen 1.',
                'short_description' => '4K OLED display and exceptional camera quality for content creators.',
                'sku' => 'SX1IV-010',
                'price' => 1399.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 70,
                'min_quantity' => 1,
                'weight' => 0.23,
                'dimensions' => '165.1 x 71.1 x 8.2 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/71u9nmoS6oL._AC_SX679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51jzgD+Iq7L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/51xGJS2jcaL._AC_SX679_.jpg"]',
                'meta_title' => 'Sony Xperia 1 IV - 4K Display & Pro Camera',
                'meta_description' => 'Sony Xperia 1 IV offers a 4K OLED display and a professional camera system for creators.',
                'rating_average' => 4.4,
                'rating_count' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 10
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 14 Pro Max',
                'slug' => 'iphone-14-pro-max',
                'description' => 'The iPhone 14 Pro Max comes with a 48 MP main camera, a 6.7-inch OLED display, and the new A16 Bionic chip.',
                'short_description' => 'Flagship iPhone with A16 Bionic chip and 48 MP camera.',
                'sku' => 'IP14PM-001',
                'price' => 1099.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 150,
                'min_quantity' => 1,
                'weight' => 0.24,
                'dimensions' => '160.8 x 78.1 x 7.85 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/513FAMDqgXL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51CM4kw8LrL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/61kAvg-cnsL._AC_SY679_.jpg"]',
                'meta_title' => 'iPhone 14 Pro Max - 48 MP Camera & A16 Bionic Chip',
                'meta_description' => 'Discover the iPhone 14 Pro Max with the powerful A16 chip and 48 MP main camera for stunning photos.',
                'rating_average' => 4.9,
                'rating_count' => 1500,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Product 11
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 14 Pro',
                'slug' => 'iphone-14-pro',
                'description' => 'The iPhone 14 Pro features a 48 MP camera system, a 6.1-inch OLED display, and the A16 Bionic chip for powerful performance.',
                'short_description' => 'Premium iPhone with A16 Bionic chip and 48 MP camera system.',
                'sku' => 'IP14P-002',
                'price' => 999.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 0.21,
                'dimensions' => '147.5 x 71.5 x 7.85 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61XO4bORHUL._AC_SX679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71UFfinJO1L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/711yt5-rPLL._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone 14 Pro - 48 MP Camera & A16 Bionic Chip',
                'meta_description' => 'Get the iPhone 14 Pro with powerful A16 Bionic chip, 48 MP main camera, and exceptional performance.',
                'rating_average' => 4.8,
                'rating_count' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 12
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 13 Mini',
                'slug' => 'iphone-13-mini',
                'description' => 'The iPhone 13 Mini offers a 12 MP camera, 5.4-inch OLED display, and the powerful A15 Bionic chip.',
                'short_description' => 'Compact iPhone with A15 Bionic chip and excellent camera.',
                'sku' => 'IP13M-003',
                'price' => 699.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 220,
                'min_quantity' => 1,
                'weight' => 0.14,
                'dimensions' => '131.5 x 64.2 x 7.65 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61H3jeeHnUL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/6106xNztgVL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/51lOLUY7fsL._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone 13 Mini - Compact & Powerful',
                'meta_description' => 'iPhone 13 Mini delivers exceptional performance and a 12 MP camera in a compact size.',
                'rating_average' => 4.7,
                'rating_count' => 950,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 13
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 13',
                'slug' => 'iphone-13',
                'description' => 'The iPhone 13 comes with a 12 MP camera system, 6.1-inch OLED display, and A15 Bionic chip for powerful performance.',
                'short_description' => 'Flagship performance with a 12 MP camera and A15 Bionic chip.',
                'sku' => 'IP13-004',
                'price' => 799.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 250,
                'min_quantity' => 1,
                'weight' => 0.17,
                'dimensions' => '146.7 x 71.5 x 7.65 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/71MKNCEgE6L.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/812l8+7UaML._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/818vSH-K1UL._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone 13 - A15 Bionic Chip & 12 MP Camera',
                'meta_description' => 'Experience the power of the A15 Bionic chip with iPhone 13 and its exceptional 12 MP camera system.',
                'rating_average' => 4.8,
                'rating_count' => 1100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 14
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone SE (2022)',
                'slug' => 'iphone-se-2022',
                'description' => 'The iPhone SE (2022) offers the power of the A15 Bionic chip in a compact and affordable form, with a 12 MP camera and a 4.7-inch Retina HD display.',
                'short_description' => 'Affordable iPhone with A15 Bionic chip and 12 MP camera.',
                'sku' => 'IPSE2022-005',
                'price' => 429.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 300,
                'min_quantity' => 1,
                'weight' => 0.15,
                'dimensions' => '138.4 x 67.3 x 7.3 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61-wAIWB8NL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/81g7fKU1N9L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/81ypt9cvt2L._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone SE (2022) - A15 Bionic Chip',
                'meta_description' => 'iPhone SE (2022) combines the power of A15 Bionic with a compact 4.7-inch display and 12 MP camera.',
                'rating_average' => 4.6,
                'rating_count' => 850,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 15
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 12',
                'slug' => 'iphone-12',
                'description' => 'The iPhone 12 offers a 12 MP camera, 6.1-inch OLED display, and the A14 Bionic chip for fast performance.',
                'short_description' => 'iPhone with A14 Bionic chip and 12 MP camera.',
                'sku' => 'IP12-006',
                'price' => 799.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 350,
                'min_quantity' => 1,
                'weight' => 0.16,
                'dimensions' => '146.7 x 71.5 x 7.4 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51fYXSnSu9L.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51dRIfZdPsL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/51XEzNvKpKL._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone 12 - A14 Bionic Chip & 12 MP Camera',
                'meta_description' => 'Get the iPhone 12 with A14 Bionic chip, 12 MP camera, and 6.1-inch OLED display.',
                'rating_average' => 4.7,
                'rating_count' => 1100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Product 16
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 12 Pro Max',
                'slug' => 'iphone-12-pro-max',
                'description' => 'The iPhone 12 Pro Max features a 12 MP camera, 6.7-inch OLED display, and A14 Bionic chip, delivering exceptional performance and camera quality.',
                'short_description' => 'Flagship iPhone with 12 MP camera, 6.7-inch OLED display, and A14 Bionic chip.',
                'sku' => 'IP12PM-007',
                'price' => 1099.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 250,
                'min_quantity' => 1,
                'weight' => 0.23,
                'dimensions' => '160.8 x 78.1 x 7.4 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/41SLL9Zws6L.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/31fWmQEbkYL._AC_.jpg", "https://m.media-amazon.com/images/I/51liLXhX1bL._AC_SX569_.jpg"]',
                'meta_title' => 'iPhone 12 Pro Max - A14 Bionic & 12 MP Camera',
                'meta_description' => 'The iPhone 12 Pro Max brings an enhanced experience with A14 Bionic chip and a pro-level camera system.',
                'rating_average' => 4.8,
                'rating_count' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 17
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 11',
                'slug' => 'iphone-11',
                'description' => 'The iPhone 11 comes with a 12 MP dual-camera system, 6.1-inch LCD display, and the A13 Bionic chip.',
                'short_description' => 'Affordable iPhone with A13 Bionic chip and 12 MP dual-camera system.',
                'sku' => 'IP11-008',
                'price' => 699.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 300,
                'min_quantity' => 1,
                'weight' => 0.19,
                'dimensions' => '150.9 x 75.7 x 8.3 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61Y3GhJ3PRL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61lSYj5EBSL._AC_SY679_.jpg", "https://m.media-amazon.com/images/I/71E1IffTukL._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone 11 - A13 Bionic Chip & Dual-Camera System',
                'meta_description' => 'The iPhone 11 features a 12 MP dual-camera system, A13 Bionic chip, and a 6.1-inch LCD display.',
                'rating_average' => 4.7,
                'rating_count' => 1300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 18
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone XR',
                'slug' => 'iphone-xr',
                'description' => 'The iPhone XR features a 12 MP single-camera system, 6.1-inch LCD display, and the A12 Bionic chip.',
                'short_description' => 'Affordable iPhone with A12 Bionic chip and 12 MP camera.',
                'sku' => 'IPXR-009',
                'price' => 499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 350,
                'min_quantity' => 1,
                'weight' => 0.19,
                'dimensions' => '150.9 x 75.7 x 8.3 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51z1UO6N6LL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/41HNIwtMW5L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/41+bUI4jjQL._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone XR - A12 Bionic & 12 MP Camera',
                'meta_description' => 'The iPhone XR combines the A12 Bionic chip with a 12 MP camera for a great iPhone experience.',
                'rating_average' => 4.6,
                'rating_count' => 1400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 19
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 11 Pro',
                'slug' => 'iphone-11-pro',
                'description' => 'The iPhone 11 Pro features a triple-camera system with 12 MP lenses, a 5.8-inch OLED display, and the A13 Bionic chip.',
                'short_description' => 'Premium iPhone with A13 Bionic chip and triple-camera system.',
                'sku' => 'IP11P-010',
                'price' => 999.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 0.19,
                'dimensions' => '144 x 71.4 x 8.1 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61UC1mk6dfL._AC_SX679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61UC1mk6dfL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/51TaXvzHHqL._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone 11 Pro - A13 Bionic & Triple-Camera System',
                'meta_description' => 'The iPhone 11 Pro offers an excellent triple-camera system, A13 Bionic chip, and a stunning OLED display.',
                'rating_average' => 4.8,
                'rating_count' => 1100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 20
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'MacBook Pro 16-inch (M2 Pro)',
                'slug' => 'macbook-pro-16-inch-m2-pro',
                'description' => 'The MacBook Pro 16-inch (M2 Pro) features a powerful M2 Pro chip, a 16-inch Retina display, and up to 64GB of RAM.',
                'short_description' => 'Powerful MacBook Pro with M2 Pro chip and 16-inch Retina display.',
                'sku' => 'MBP16M2-001',
                'price' => 2499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 50,
                'min_quantity' => 1,
                'weight' => 2.10,
                'dimensions' => '356.4 x 245.9 x 16.8 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61C9irOOQVL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71-uDe4TN1L._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/61ldExf7mbL._AC_SX522_.jpg"]',
                'meta_title' => 'MacBook Pro 16-inch (M2 Pro) - Power and Performance',
                'meta_description' => 'The MacBook Pro 16-inch (M2 Pro) offers exceptional performance with the M2 Pro chip, perfect for professionals.',
                'rating_average' => 4.9,
                'rating_count' => 400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 21
            [
                'category_id' => 6,
                'subcategory_id' => 6,
                'name' => 'iPhone 11 Pro',
                'slug' => 'iphone-11-pro',
                'description' => 'The iPhone 11 Pro features a triple-camera system with 12 MP lenses, a 5.8-inch OLED display, and the A13 Bionic chip.',
                'short_description' => 'Premium iPhone with A13 Bionic chip and triple-camera system.',
                'sku' => 'IP11P-010',
                'price' => 999.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 0.19,
                'dimensions' => '144 x 71.4 x 8.1 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61UC1mk6dfL._AC_SX679_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61UC1mk6dfL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/51TaXvzHHqL._AC_SX679_.jpg"]',
                'meta_title' => 'iPhone 11 Pro - A13 Bionic & Triple-Camera System',
                'meta_description' => 'The iPhone 11 Pro offers an excellent triple-camera system, A13 Bionic chip, and a stunning OLED display.',
                'rating_average' => 4.8,
                'rating_count' => 1100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 22
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'MacBook Pro 16-inch (M2 Pro)',
                'slug' => 'macbook-pro-16-inch-m2-pro',
                'description' => 'The MacBook Pro 16-inch (M2 Pro) features a powerful M2 Pro chip, a 16-inch Retina display, and up to 64GB of RAM.',
                'short_description' => 'Powerful MacBook Pro with M2 Pro chip and 16-inch Retina display.',
                'sku' => 'MBP16M2-001',
                'price' => 2499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 50,
                'min_quantity' => 1,
                'weight' => 2.10,
                'dimensions' => '356.4 x 245.9 x 16.8 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61C9irOOQVL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71-uDe4TN1L._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/61ldExf7mbL._AC_SX522_.jpg"]',
                'meta_title' => 'MacBook Pro 16-inch (M2 Pro) - Power and Performance',
                'meta_description' => 'The MacBook Pro 16-inch (M2 Pro) offers exceptional performance with the M2 Pro chip, perfect for professionals.',
                'rating_average' => 4.9,
                'rating_count' => 400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 23
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'Dell XPS 13',
                'slug' => 'dell-xps-13',
                'description' => 'The Dell XPS 13 is a premium ultrabook featuring an Intel Core i7 processor, a 13.4-inch FHD+ display, and a sleek design.',
                'short_description' => 'Premium ultrabook with Intel Core i7 and 13.4-inch FHD+ display.',
                'sku' => 'DXPS13-002',
                'price' => 1199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 150,
                'min_quantity' => 1,
                'weight' => 1.20,
                'dimensions' => '295.7 x 198.7 x 14.8 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/71jPjHrYs-L._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71D9fJcvqsL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/71fgSHzth5L._AC_SX522_.jpg"]',
                'meta_title' => 'Dell XPS 13 - Premium Ultrabook',
                'meta_description' => 'The Dell XPS 13 offers exceptional performance with Intel Core i7 and a stunning FHD+ display.',
                'rating_average' => 4.8,
                'rating_count' => 950,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 24
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'HP Spectre x360',
                'slug' => 'hp-spectre-x360',
                'description' => 'The HP Spectre x360 is a 2-in-1 convertible laptop with an Intel Core i7 processor, 13.3-inch OLED display, and premium design.',
                'short_description' => 'Premium 2-in-1 laptop with Intel Core i7 and 13.3-inch OLED display.',
                'sku' => 'HPSX360-003',
                'price' => 1399.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 120,
                'min_quantity' => 1,
                'weight' => 1.30,
                'dimensions' => '306.0 x 194.5 x 13.6 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/81ZvaBihNsL.__AC_SY300_SX300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/81BmB0Mx2rL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/81xDoHsXl+L._AC_SX522_.jpg"]',
                'meta_title' => 'HP Spectre x360 - 2-in-1 Laptop',
                'meta_description' => 'The HP Spectre x360 offers a premium 2-in-1 experience with Intel Core i7 and OLED display.',
                'rating_average' => 4.7,
                'rating_count' => 800,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 25
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'Lenovo ThinkPad X1 Carbon',
                'slug' => 'lenovo-thinkpad-x1-carbon',
                'description' => 'The Lenovo ThinkPad X1 Carbon is an ultrabook with Intel Core i7, a 14-inch FHD display, and lightweight design, perfect for professionals.',
                'short_description' => 'Lightweight and powerful ultrabook with Intel Core i7 and 14-inch FHD display.',
                'sku' => 'LTX1C-004',
                'price' => 1599.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 100,
                'min_quantity' => 1,
                'weight' => 1.10,
                'dimensions' => '314.4 x 221.3 x 14.9 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61GSvJjxBuL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51q4xuGWAVL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/61VVypCqZxL._AC_SX522_.jpg"]',
                'meta_title' => 'Lenovo ThinkPad X1 Carbon - Lightweight Power',
                'meta_description' => 'Lenovo ThinkPad X1 Carbon offers the perfect combination of performance, portability, and professional design.',
                'rating_average' => 4.8,
                'rating_count' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             // Product 26
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'Microsoft Surface Laptop 4',
                'slug' => 'microsoft-surface-laptop-4',
                'description' => 'The Microsoft Surface Laptop 4 features a 13.5-inch PixelSense display, Intel Core i7, and up to 32GB of RAM, delivering excellent performance.',
                'short_description' => 'Premium laptop with Intel Core i7 and 13.5-inch PixelSense display.',
                'sku' => 'MSL4-005',
                'price' => 1499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 110,
                'min_quantity' => 1,
                'weight' => 1.30,
                'dimensions' => '308.1 x 223.3 x 14.5 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/813XDi6sQ3L._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71BaUXbaXsL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/813XDi6sQ3L._AC_SX522_.jpg"]',
                'meta_title' => 'Microsoft Surface Laptop 4 - Performance and Design',
                'meta_description' => 'Microsoft Surface Laptop 4 delivers excellent performance with Intel Core i7, a stunning PixelSense display, and premium design.',
                'rating_average' => 4.7,
                'rating_count' => 750,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 27
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'ASUS ROG Zephyrus G14',
                'slug' => 'asus-rog-zephyrus-g14',
                'description' => 'The ASUS ROG Zephyrus G14 is a gaming laptop featuring an AMD Ryzen 9, NVIDIA RTX 3060, and a 14-inch FHD display.',
                'short_description' => 'Compact gaming laptop with Ryzen 9 and NVIDIA RTX 3060.',
                'sku' => 'ASUSZG14-006',
                'price' => 1499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 90,
                'min_quantity' => 1,
                'weight' => 1.70,
                'dimensions' => '319.3 x 222.4 x 19.9 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51Qqql9yRaL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71zNU5UBINL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/61nfhIdrzTL._AC_SX522_.jpg"]',
                'meta_title' => 'ASUS ROG Zephyrus G14 - Gaming Power',
                'meta_description' => 'The ASUS ROG Zephyrus G14 is a powerful and portable gaming laptop, offering top-tier performance with AMD Ryzen 9 and RTX 3060.',
                'rating_average' => 4.8,
                'rating_count' => 620,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 28
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'Acer Swift 3',
                'slug' => 'acer-swift-3',
                'description' => 'The Acer Swift 3 is a lightweight ultrabook featuring an Intel Core i5 processor, 14-inch Full HD display, and long battery life.',
                'short_description' => 'Lightweight ultrabook with Intel Core i5 and 14-inch Full HD display.',
                'sku' => 'ASW3-007',
                'price' => 749.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 160,
                'min_quantity' => 1,
                'weight' => 1.20,
                'dimensions' => '323.5 x 214.3 x 15.95 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61gKkYQn6lL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/81w4nBxLSyL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/51JDZf0znWL._AC_SX522_.jpg"]',
                'meta_title' => 'Acer Swift 3 - Ultra-Light Performance',
                'meta_description' => 'The Acer Swift 3 is a sleek and portable ultrabook with Intel Core i5 and long-lasting battery life.',
                'rating_average' => 4.6,
                'rating_count' => 700,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 29
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'HP Envy 13',
                'slug' => 'hp-envy-13',
                'description' => 'The HP Envy 13 is a sleek ultrabook powered by an Intel Core i7, with a 13.3-inch Full HD display, offering strong performance and premium build quality.',
                'short_description' => 'Sleek ultrabook with Intel Core i7 and 13.3-inch Full HD display.',
                'sku' => 'HPE13-008',
                'price' => 999.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 140,
                'min_quantity' => 1,
                'weight' => 1.30,
                'dimensions' => '306.0 x 194.5 x 14.9 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/41wjv9W9z7L._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61aU4Al4URL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/41wjv9W9z7L._AC_SX522_.jpg"]',
                'meta_title' => 'HP Envy 13 - Premium Ultrabook',
                'meta_description' => 'HP Envy 13 combines powerful Intel Core i7 performance with a sleek design and a stunning Full HD display.',
                'rating_average' => 4.7,
                'rating_count' => 850,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 30
            [
                'category_id' => 7,
                'subcategory_id' => 7,
                'name' => 'Apple MacBook Air (M2)',
                'slug' => 'apple-macbook-air-m2',
                'description' => 'The Apple MacBook Air (M2) features the new M2 chip, 13.6-inch Liquid Retina display, and up to 18 hours of battery life.',
                'short_description' => 'Lightweight ultrabook with M2 chip and 13.6-inch Liquid Retina display.',
                'sku' => 'AMBA-M2-009',
                'price' => 1199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 120,
                'min_quantity' => 1,
                'weight' => 1.20,
                'dimensions' => '304.1 x 215.0 x 11.3 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/719C6bJv8jL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71ifX4fhbnL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/81nHRHmUbaL._AC_SX522_.jpg"]',
                'meta_title' => 'Apple MacBook Air (M2) - Lightweight and Powerful',
                'meta_description' => 'The MacBook Air with M2 chip delivers an ultra-light and ultra-powerful experience with up to 18 hours of battery life.',
                'rating_average' => 4.8,
                'rating_count' => 900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             // Product 31
            [
                'category_id' => 7,
                'subcategory_id' => 8,
                'name' => 'MSI GE76 Raider',
                'slug' => 'msi-ge76-raider',
                'description' => 'The MSI GE76 Raider is a powerful gaming laptop with an Intel Core i9, NVIDIA GeForce RTX 3080, and a 17.3-inch 4K display.',
                'short_description' => 'High-performance gaming laptop with Intel Core i9 and RTX 3080.',
                'sku' => 'MSIGE76-010',
                'price' => 2299.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 80,
                'min_quantity' => 1,
                'weight' => 2.40,
                'dimensions' => '399.5 x 299.5 x 25.9 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51Q1cRNQ7JS._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51f6D7wczDS._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/41hL0Y2mN5S._AC_SX522_.jpg"]',
                'meta_title' => 'MSI GE76 Raider - Ultimate Gaming Performance',
                'meta_description' => 'MSI GE76 Raider delivers top-tier gaming performance with Intel Core i9 and NVIDIA RTX 3080, perfect for hardcore gamers.',
                'rating_average' => 4.9,
                'rating_count' => 500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 32
            [
                'category_id' => 7,
                'subcategory_id' => 8,
                'name' => 'Corsair Vengeance i7200',
                'slug' => 'corsair-vengeance-i7200',
                'description' => 'The Corsair Vengeance i7200 is a high-performance gaming desktop featuring an Intel Core i9 processor, NVIDIA GeForce RTX 3080, and 32GB of RAM.',
                'short_description' => 'High-performance gaming desktop with Intel Core i9 and RTX 3080.',
                'sku' => 'CVi7200-006',
                'price' => 2499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 60,
                'min_quantity' => 1,
                'weight' => 15.00,
                'dimensions' => '440 x 200 x 480 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/41AAfzJALNL._SX342_SY445_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/91Xq7GgI4DL._SX522_.jpg", "https://m.media-amazon.com/images/I/8190c5BI-ML._SX522_.jpg"]',
                'meta_title' => 'Corsair Vengeance i7200 - Ultimate Gaming Performance',
                'meta_description' => 'The Corsair Vengeance i7200 provides ultimate gaming performance with Intel Core i9 and RTX 3080 graphics.',
                'rating_average' => 4.9,
                'rating_count' => 450,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 33
            [
                'category_id' => 7,
                'subcategory_id' => 8,
                'name' => 'Alienware Aurora R13',
                'slug' => 'alienware-aurora-r13',
                'description' => 'The Alienware Aurora R13 is a high-end gaming desktop featuring an Intel Core i9 processor, NVIDIA GeForce RTX 3080, and customizable RGB lighting.',
                'short_description' => 'High-performance gaming desktop with Intel Core i9 and RTX 3080.',
                'sku' => 'AWAUR13-007',
                'price' => 2899.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 40,
                'min_quantity' => 1,
                'weight' => 18.80,
                'dimensions' => '495 x 220 x 520 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/711bPPfIEKL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51W-jUn+TFL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/51VZcVYhMHL._AC_SX522_.jpg"]',
                'meta_title' => 'Alienware Aurora R13 - Ultimate Gaming Rig',
                'meta_description' => 'Alienware Aurora R13 offers premium gaming performance with Intel Core i9 and RTX 3080, ideal for the most demanding tasks.',
                'rating_average' => 5.0,
                'rating_count' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 34
            [
                'category_id' => 7,
                'subcategory_id' => 8,
                'name' => 'Lenovo Legion Tower 5',
                'slug' => 'lenovo-legion-tower-5',
                'description' => 'The Lenovo Legion Tower 5 is a powerful gaming desktop featuring an AMD Ryzen 7 processor, NVIDIA GeForce RTX 3060, and 16GB of RAM.',
                'short_description' => 'Gaming desktop with AMD Ryzen 7 and NVIDIA RTX 3060.',
                'sku' => 'LLT5-008',
                'price' => 1599.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 70,
                'min_quantity' => 1,
                'weight' => 14.00,
                'dimensions' => '444 x 208 x 422 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51gCkG0st0L.__AC_SY300_SX300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51WaloPLD5L._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/51d8sLjAF6L._AC_SX522_.jpg"]',
                'meta_title' => 'Lenovo Legion Tower 5 - Gaming Power',
                'meta_description' => 'The Lenovo Legion Tower 5 is built for serious gamers, offering incredible performance with Ryzen 7 and RTX 3060.',
                'rating_average' => 4.8,
                'rating_count' => 400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 35
            [
                'category_id' => 7,
                'subcategory_id' => 8,
                'name' => 'Acer Predator Orion 5000',
                'slug' => 'acer-predator-orion-5000',
                'description' => 'The Acer Predator Orion 5000 is a high-performance gaming desktop featuring an Intel Core i9, NVIDIA GeForce RTX 3080, and 32GB of RAM.',
                'short_description' => 'Ultimate gaming desktop with Intel Core i9 and NVIDIA RTX 3080.',
                'sku' => 'APO5000-009',
                'price' => 2899.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 50,
                'min_quantity' => 1,
                'weight' => 16.00,
                'dimensions' => '478 x 220 x 510 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/714i7HWRV9L._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61YS1TRSzzL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/51Fo6zPEsfL._AC_SX522_.jpg"]',
                'meta_title' => 'Acer Predator Orion 5000 - Extreme Gaming Power',
                'meta_description' => 'Acer Predator Orion 5000 delivers extreme performance with Intel Core i9, RTX 3080, and massive RAM for smooth gaming.',
                'rating_average' => 5.0,
                'rating_count' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
              // Product 36
            [
                'category_id' => 7,
                'subcategory_id' => 8,
                'name' => 'CyberPowerPC Gamer Xtreme VR',
                'slug' => 'cyberpowerpc-gamer-xtreme-vr',
                'description' => 'The CyberPowerPC Gamer Xtreme VR is a high-performance gaming desktop featuring an Intel Core i7 processor, NVIDIA GeForce RTX 3070, and 16GB of RAM, designed for virtual reality gaming.',
                'short_description' => 'High-performance gaming desktop with Intel Core i7, RTX 3070, and VR support.',
                'sku' => 'CPXG-XR-010',
                'price' => 1699.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 80,
                'min_quantity' => 1,
                'weight' => 14.50,
                'dimensions' => '440 x 200 x 480 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/71ENeVg0MuL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61BkRNIaJZL._AC_SX522_.jpg", "chromewebstore.google.com/category/themes/dark"]',
                'meta_title' => 'CyberPowerPC Gamer Xtreme VR - VR Ready Gaming',
                'meta_description' => 'The CyberPowerPC Gamer Xtreme VR provides exceptional performance with Intel Core i7 and RTX 3070, perfect for VR gaming.',
                'rating_average' => 4.8,
                'rating_count' => 350,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 37
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'PlayStation 5',
                'slug' => 'playstation-5',
                'description' => 'The PlayStation 5 is Sony’s next-generation gaming console, featuring lightning-fast load times, stunning graphics, and a new controller with adaptive triggers.',
                'short_description' => 'Next-gen gaming console with fast load times and stunning graphics.',
                'sku' => 'PS5-001',
                'price' => 499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 200,
                'min_quantity' => 1,
                'weight' => 4.50,
                'dimensions' => '390 x 104 x 260 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/41TnqQ0prBL._SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61Ue9AisGGL._SX522_.jpg", "https://m.media-amazon.com/images/I/41tVr19I3zL._SX522_.jpg"]',
                'meta_title' => 'PlayStation 5 - Next-Gen Gaming',
                'meta_description' => 'PlayStation 5 offers ultra-fast load times, incredible graphics, and immersive gameplay.',
                'rating_average' => 4.9,
                'rating_count' => 1500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 38
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'Xbox Series X',
                'slug' => 'xbox-series-x',
                'description' => 'The Xbox Series X is the most powerful gaming console from Microsoft, offering 4K gaming, fast load times, and backward compatibility for older Xbox games.',
                'short_description' => 'Most powerful Xbox console with 4K gaming and fast load times.',
                'sku' => 'XSX-002',
                'price' => 499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 4.40,
                'dimensions' => '301 x 151 x 151 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/31sh9XqMZxL._SY430_SX215_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61QS7gvhulL._SX522_.jpg", "https://m.media-amazon.com/images/I/71PowBNfNyL._SX522_.jpg"]',
                'meta_title' => 'Xbox Series X - Ultimate Gaming Experience',
                'meta_description' => 'The Xbox Series X delivers stunning 4K gaming, lightning-fast load times, and compatibility with older Xbox games.',
                'rating_average' => 4.8,
                'rating_count' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 39
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'Nintendo Switch OLED',
                'slug' => 'nintendo-switch-oled',
                'description' => 'The Nintendo Switch OLED offers a 7-inch OLED screen, improved audio, and more storage for handheld gaming.',
                'short_description' => 'Handheld gaming with 7-inch OLED screen and improved audio.',
                'sku' => 'NSO-003',
                'price' => 349.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 220,
                'min_quantity' => 1,
                'weight' => 0.42,
                'dimensions' => '102 x 242 x 13.9 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/41zNqLiOenL._SY300_SX300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61E4b5drxzS._SX522_.jpg", "https://m.media-amazon.com/images/I/6106vjwmtIS._SX522_.jpg"]',
                'meta_title' => 'Nintendo Switch OLED - Enhanced Handheld Gaming',
                'meta_description' => 'The Nintendo Switch OLED features a beautiful 7-inch OLED display, enhanced audio, and more storage for a superior gaming experience.',
                'rating_average' => 4.7,
                'rating_count' => 1100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 40
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'PlayStation VR2',
                'slug' => 'playstation-vr2',
                'description' => 'PlayStation VR2 offers a revolutionary virtual reality experience with 4K HDR display, enhanced tracking, and immersive sound design.',
                'short_description' => 'Next-gen VR headset for PlayStation 5 with 4K HDR and immersive audio.',
                'sku' => 'PSVR2-004',
                'price' => 549.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 150,
                'min_quantity' => 1,
                'weight' => 0.56,
                'dimensions' => '200 x 210 x 110 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51G8NFN0AFL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51w-Bh8KdxL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/61qjZlJORML._AC_SX522_.jpg"]',
                'meta_title' => 'PlayStation VR2 - Immersive Virtual Reality Experience',
                'meta_description' => 'The PlayStation VR2 offers stunning visuals and immersive sound for a next-gen virtual reality experience on PlayStation 5.',
                'rating_average' => 4.9,
                'rating_count' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

             // Product 41
            [
                'category_id' => 7,
                'subcategory_id' => 8,
                'name' => 'Xbox One X',
                'slug' => 'xbox-one-x',
                'description' => 'The Xbox One X offers a true 4K gaming experience, with HDR and a powerful GPU, designed to provide the best console gaming experience.',
                'short_description' => '4K gaming console with HDR support and powerful GPU.',
                'sku' => 'X1X-005',
                'price' => 499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 4.40,
                'dimensions' => '300 x 240 x 60 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61LVSqb4BHL._SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/711NQrvQt9L._SX522_.jpg", "https://m.media-amazon.com/images/I/61hfJC2KtyL._SX522_.jpg"]',
                'meta_title' => 'Xbox One X - Ultimate 4K Gaming Experience',
                'meta_description' => 'The Xbox One X offers a powerful 4K gaming experience with HDR and seamless performance for gamers.',
                'rating_average' => 4.7,
                'rating_count' => 950,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 42
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'Nintendo Switch Lite',
                'slug' => 'nintendo-switch-lite',
                'description' => 'The Nintendo Switch Lite is a handheld-only version of the Nintendo Switch, featuring a 5.5-inch display and a compact design.',
                'short_description' => 'Compact handheld gaming console with 5.5-inch display.',
                'sku' => 'NSLITE-006',
                'price' => 199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 250,
                'min_quantity' => 1,
                'weight' => 0.28,
                'dimensions' => '102 x 239 x 13.9 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51OKn0Ci6TL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51OKn0Ci6TL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/51sD9ag6AGL.__AC_SX300_SY300_QL70_FMwebp_.jpg"]',
                'meta_title' => 'Nintendo Switch Lite - Compact Handheld Gaming',
                'meta_description' => 'The Nintendo Switch Lite is a handheld-only gaming console offering portable gameplay with a 5.5-inch display.',
                'rating_average' => 4.6,
                'rating_count' => 1300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 43
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'PlayStation 4 Pro',
                'slug' => 'playstation-4-pro',
                'description' => 'The PlayStation 4 Pro offers a 4K gaming experience, enhanced performance, and a wide selection of games to choose from.',
                'short_description' => 'Experience 4K gaming with enhanced performance and a large game library.',
                'sku' => 'PS4P-007',
                'price' => 399.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 200,
                'min_quantity' => 1,
                'weight' => 3.50,
                'dimensions' => '295 x 55 x 327 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61niTZ3ETRL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71BdLcs8eEL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/61bjDrhSQjL._AC_SX522_.jpg"]',
                'meta_title' => 'PlayStation 4 Pro - 4K Gaming Experience',
                'meta_description' => 'PlayStation 4 Pro offers enhanced 4K gaming, providing a great experience for those looking for a better PlayStation performance.',
                'rating_average' => 4.6,
                'rating_count' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 44
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'Xbox Series S',
                'slug' => 'xbox-series-s',
                'description' => 'The Xbox Series S is a compact, next-gen gaming console offering a 1440p resolution, fast load times, and access to Xbox Game Pass.',
                'short_description' => 'Compact next-gen console with 1440p gaming and Game Pass.',
                'sku' => 'XSS-008',
                'price' => 299.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 250,
                'min_quantity' => 1,
                'weight' => 1.90,
                'dimensions' => '275 x 151 x 63.5 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61x8fR-8vXL._SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61s7Rg8GHSL._SX522_.jpg", "https://m.media-amazon.com/images/I/61tn-8-ADuL._SX522_.jpg"]',
                'meta_title' => 'Xbox Series S - Compact Next-Gen Gaming',
                'meta_description' => 'The Xbox Series S is the most compact next-gen gaming console, delivering fast load times, 1440p gaming, and access to Xbox Game Pass.',
                'rating_average' => 4.7,
                'rating_count' => 1300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 45
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'Nintendo 3DS XL',
                'slug' => 'nintendo-3ds-xl',
                'description' => 'The Nintendo 3DS XL features a 4.88-inch 3D display, backward compatibility with DS games, and an extensive game library.',
                'short_description' => 'Portable handheld console with 3D display and DS compatibility.',
                'sku' => 'N3DSXL-009',
                'price' => 199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 0.33,
                'dimensions' => '156 x 91.5 x 22 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/519JCqnt5pL._SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71Ll+Lw-6YL._SX522_.jpg", "https://m.media-amazon.com/images/I/811uejh9vQL._SX522_.jpg"]',
                'meta_title' => 'Nintendo 3DS XL - Handheld 3D Gaming',
                'meta_description' => 'Enjoy 3D gaming and backward compatibility with the Nintendo 3DS XL, featuring a large display and extensive game library.',
                'rating_average' => 4.6,
                'rating_count' => 900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             // Product 46
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'PlayStation VR2',
                'slug' => 'playstation-vr2',
                'description' => 'PlayStation VR2 offers a revolutionary virtual reality experience with 4K HDR display, enhanced tracking, and immersive sound design.',
                'short_description' => 'Next-gen VR headset for PlayStation 5 with 4K HDR and immersive audio.',
                'sku' => 'PSVR2-004',
                'price' => 549.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 150,
                'min_quantity' => 1,
                'weight' => 0.56,
                'dimensions' => '200 x 210 x 110 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51G8NFN0AFL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51w-Bh8KdxL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/61qjZlJORML._AC_SX522_.jpg"]',
                'meta_title' => 'PlayStation VR2 - Immersive Virtual Reality Experience',
                'meta_description' => 'The PlayStation VR2 offers stunning visuals and immersive sound for a next-gen virtual reality experience on PlayStation 5.',
                'rating_average' => 4.9,
                'rating_count' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 47
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'Xbox One X',
                'slug' => 'xbox-one-x',
                'description' => 'The Xbox One X offers a true 4K gaming experience, with HDR and a powerful GPU, designed to provide the best console gaming experience.',
                'short_description' => '4K gaming console with HDR support and powerful GPU.',
                'sku' => 'X1X-005',
                'price' => 499.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 4.40,
                'dimensions' => '300 x 240 x 60 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61LVSqb4BHL._SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/711NQrvQt9L._SX522_.jpg", "https://m.media-amazon.com/images/I/61hfJC2KtyL._SX522_.jpg"]',
                'meta_title' => 'Xbox One X - Ultimate 4K Gaming Experience',
                'meta_description' => 'The Xbox One X offers a powerful 4K gaming experience with HDR and seamless performance for gamers.',
                'rating_average' => 4.7,
                'rating_count' => 950,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 48
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'Nintendo Switch Lite',
                'slug' => 'nintendo-switch-lite',
                'description' => 'The Nintendo Switch Lite is a handheld-only version of the Nintendo Switch, featuring a 5.5-inch display and a compact design.',
                'short_description' => 'Compact handheld gaming console with 5.5-inch display.',
                'sku' => 'NSLITE-006',
                'price' => 199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 250,
                'min_quantity' => 1,
                'weight' => 0.28,
                'dimensions' => '102 x 239 x 13.9 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51OKn0Ci6TL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51OKn0Ci6TL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/51sD9ag6AGL.__AC_SX300_SY300_QL70_FMwebp_.jpg"]',
                'meta_title' => 'Nintendo Switch Lite - Compact Handheld Gaming',
                'meta_description' => 'The Nintendo Switch Lite is a handheld-only gaming console offering portable gameplay with a 5.5-inch display.',
                'rating_average' => 4.6,
                'rating_count' => 1300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 49
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'Logitech G Pro X Wireless Headset',
                'slug' => 'logitech-g-pro-x-wireless-headset',
                'description' => 'The Logitech G Pro X Wireless Headset is designed for pro-level gaming, featuring 7.1 surround sound, wireless freedom, and exceptional comfort.',
                'short_description' => 'Wireless gaming headset with 7.1 surround sound and exceptional comfort.',
                'sku' => 'LGXW-001',
                'price' => 199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 150,
                'min_quantity' => 1,
                'weight' => 0.37,
                'dimensions' => '180 x 190 x 80 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51Vqs9NufmL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51Vqs9NufmL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/51Vqs9NufmL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "image3.jpg"]',
                'meta_title' => 'Logitech G Pro X Wireless Headset - Pro-Level Gaming',
                'meta_description' => 'The Logitech G Pro X Wireless Headset offers pro-level audio quality and comfort with wireless freedom and 7.1 surround sound.',
                'rating_average' => 4.8,
                'rating_count' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 50
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'Razer Nari Ultimate Wireless Headset',
                'slug' => 'razer-nari-ultimate-wireless-headset',
                'description' => 'The Razer Nari Ultimate Wireless Headset features Hypersense technology, 7.1 surround sound, and cooling gel-infused ear cushions for ultimate comfort.',
                'short_description' => 'Wireless gaming headset with Hypersense technology and 7.1 surround sound.',
                'sku' => 'RNUIWH-002',
                'price' => 249.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 120,
                'min_quantity' => 1,
                'weight' => 0.39,
                'dimensions' => '196 x 255 x 108 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/81f6DNi4TFL.__AC_SY300_SX300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71iYNikqhLL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/71DVsLf2E8L._AC_SX522_.jpg"]',
                'meta_title' => 'Razer Nari Ultimate Wireless Headset - Ultimate Comfort',
                'meta_description' => 'The Razer Nari Ultimate Wireless Headset delivers immersive 7.1 surround sound and maximum comfort with Hypersense technology and cooling ear cushions.',
                'rating_average' => 4.7,
                'rating_count' => 850,
                'created_at' => now(),
                'updated_at' => now(),
            ],

              // Product 51
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'Nintendo 3DS XL',
                'slug' => 'nintendo-3ds-xl',
                'description' => 'The Nintendo 3DS XL features a 4.88-inch 3D display, backward compatibility with DS games, and an extensive game library.',
                'short_description' => 'Portable handheld console with 3D display and DS compatibility.',
                'sku' => 'N3DSXL-009',
                'price' => 199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 180,
                'min_quantity' => 1,
                'weight' => 0.33,
                'dimensions' => '156 x 91.5 x 22 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/519JCqnt5pL._SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71Ll+Lw-6YL._SX522_.jpg", "https://m.media-amazon.com/images/I/811uejh9vQL._SX522_.jpg"]',
                'meta_title' => 'Nintendo 3DS XL - Handheld 3D Gaming',
                'meta_description' => 'Enjoy 3D gaming and backward compatibility with the Nintendo 3DS XL, featuring a large display and extensive game library.',
                'rating_average' => 4.6,
                'rating_count' => 900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 52
            [
                'category_id' => 8,
                'subcategory_id' => 9,
                'name' => 'PlayStation 4 Slim',
                'slug' => 'playstation-4-slim',
                'description' => 'The PlayStation 4 Slim is a compact version of the PS4 with the same great gaming performance, 500GB of storage, and access to a wide selection of games.',
                'short_description' => 'Compact PlayStation with 500GB storage and great gaming performance.',
                'sku' => 'PS4S-010',
                'price' => 299.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 250,
                'min_quantity' => 1,
                'weight' => 2.10,
                'dimensions' => '265 x 39 x 288 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51t0bPwu8uL.__AC_SY300_SX300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/41YGPVMh6PL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/61+Ufg4Je5L._AC_SX522_.jpg"]',
                'meta_title' => 'PlayStation 4 Slim - Compact and Powerful',
                'meta_description' => 'The PlayStation 4 Slim provides a compact design, 500GB storage, and access to thousands of games.',
                'rating_average' => 4.7,
                'rating_count' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 53
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'Logitech G Pro X Wireless Headset',
                'slug' => 'logitech-g-pro-x-wireless-headset',
                'description' => 'The Logitech G Pro X Wireless Headset is designed for pro-level gaming, featuring 7.1 surround sound, wireless freedom, and exceptional comfort.',
                'short_description' => 'Wireless gaming headset with 7.1 surround sound and exceptional comfort.',
                'sku' => 'LGXW-001',
                'price' => 199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 150,
                'min_quantity' => 1,
                'weight' => 0.37,
                'dimensions' => '180 x 190 x 80 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/51Vqs9NufmL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/51Vqs9NufmL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/51Vqs9NufmL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "image3.jpg"]',
                'meta_title' => 'Logitech G Pro X Wireless Headset - Pro-Level Gaming',
                'meta_description' => 'The Logitech G Pro X Wireless Headset offers pro-level audio quality and comfort with wireless freedom and 7.1 surround sound.',
                'rating_average' => 4.8,
                'rating_count' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 54
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'Razer Nari Ultimate Wireless Headset',
                'slug' => 'razer-nari-ultimate-wireless-headset',
                'description' => 'The Razer Nari Ultimate Wireless Headset features Hypersense technology, 7.1 surround sound, and cooling gel-infused ear cushions for ultimate comfort.',
                'short_description' => 'Wireless gaming headset with Hypersense technology and 7.1 surround sound.',
                'sku' => 'RNUIWH-002',
                'price' => 249.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 120,
                'min_quantity' => 1,
                'weight' => 0.39,
                'dimensions' => '196 x 255 x 108 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/81f6DNi4TFL.__AC_SY300_SX300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71iYNikqhLL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/71DVsLf2E8L._AC_SX522_.jpg"]',
                'meta_title' => 'Razer Nari Ultimate Wireless Headset - Ultimate Comfort',
                'meta_description' => 'The Razer Nari Ultimate Wireless Headset delivers immersive 7.1 surround sound and maximum comfort with Hypersense technology and cooling ear cushions.',
                'rating_average' => 4.7,
                'rating_count' => 850,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 55
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'Xbox Elite Series 2 Controller',
                'slug' => 'xbox-elite-series-2-controller',
                'description' => 'The Xbox Elite Series 2 Controller features adjustable tension thumbsticks, a wrap-around rubberized grip, and a rechargeable battery for pro-level gaming.',
                'short_description' => 'Premium Xbox controller with adjustable thumbsticks and enhanced grip.',
                'sku' => 'XESC2-003',
                'price' => 179.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 200,
                'min_quantity' => 1,
                'weight' => 0.34,
                'dimensions' => '180 x 120 x 70 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/41Olt1+b1hL._SX342_SY445_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71iOjxNM8oL._SX522_.jpg", "https://m.media-amazon.com/images/I/71exTbMrnvL._SX522_.jpg"]',
                'meta_title' => 'Xbox Elite Series 2 Controller - Pro-Level Precision',
                'meta_description' => 'The Xbox Elite Series 2 Controller offers customizable thumbsticks, paddle buttons, and a durable design for ultimate gaming precision.',
                'rating_average' => 4.8,
                'rating_count' => 950,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Product 56
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'PlayStation 5 DualSense Wireless Controller',
                'slug' => 'playstation-5-dualsense-wireless-controller',
                'description' => 'The PlayStation 5 DualSense Wireless Controller offers adaptive triggers, haptic feedback, and a built-in microphone for immersive gaming.',
                'short_description' => 'Next-gen PlayStation controller with adaptive triggers and haptic feedback.',
                'sku' => 'PS5DSC-004',
                'price' => 69.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 300,
                'min_quantity' => 1,
                'weight' => 0.28,
                'dimensions' => '160 x 65 x 100 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/519ayRwl1AL._SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61cWAmAkB-L._SX522_.jpg", "https://m.media-amazon.com/images/I/61WX+8pbIjL._SX522_.jpg"]',
                'meta_title' => 'PlayStation 5 DualSense Wireless Controller - Next-Gen Gaming',
                'meta_description' => 'The PlayStation 5 DualSense controller delivers revolutionary features like adaptive triggers and haptic feedback for a next-gen gaming experience.',
                'rating_average' => 4.8,
                'rating_count' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 57
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'SteelSeries Arctis 7P Wireless Headset',
                'slug' => 'steelseries-arctis-7p-wireless-headset',
                'description' => 'The SteelSeries Arctis 7P Wireless Headset features ultra-low latency wireless audio, immersive sound, and long battery life, designed for the PlayStation 5.',
                'short_description' => 'Wireless gaming headset with ultra-low latency and long battery life for PS5.',
                'sku' => 'SS7P-005',
                'price' => 149.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 120,
                'min_quantity' => 1,
                'weight' => 0.35,
                'dimensions' => '205 x 190 x 95 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/419IybpCmdL._SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/71i9tYxx38L._SX466_.jpg", "https://m.media-amazon.com/images/I/71Z8y31XdyL._SY550_.jpg"]',
                'meta_title' => 'SteelSeries Arctis 7P Wireless Headset - Gaming Audio',
                'meta_description' => 'The SteelSeries Arctis 7P Wireless Headset delivers immersive audio and ultra-low latency for gaming on PlayStation 5.',
                'rating_average' => 4.7,
                'rating_count' => 800,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 58
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'Logitech G923 Racing Wheel',
                'slug' => 'logitech-g923-racing-wheel',
                'description' => 'The Logitech G923 Racing Wheel offers TrueForce force feedback technology, adjustable brake pedals, and a responsive racing experience for all racing games.',
                'short_description' => 'High-performance racing wheel with TrueForce force feedback and responsive pedals.',
                'sku' => 'LG923-006',
                'price' => 399.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 100,
                'min_quantity' => 1,
                'weight' => 7.50,
                'dimensions' => '279 x 264 x 278 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/41366vu2dxL._SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/713w1NjMw5L._SX522_.jpg", "https://m.media-amazon.com/images/I/71ieKMwTnVL._SX522_.jpg"]',
                'meta_title' => 'Logitech G923 Racing Wheel - TrueForce Feedback',
                'meta_description' => 'The Logitech G923 Racing Wheel offers immersive racing with TrueForce feedback and responsive pedals for a true racing experience.',
                'rating_average' => 4.6,
                'rating_count' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 59
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'Corsair K95 RGB Platinum XT Mechanical Keyboard',
                'slug' => 'corsair-k95-rgb-platinum-xt-mechanical-keyboard',
                'description' => 'The Corsair K95 RGB Platinum XT Mechanical Keyboard features Cherry MX switches, customizable RGB backlighting, and programmable macro keys.',
                'short_description' => 'Premium mechanical keyboard with RGB backlighting and macro keys.',
                'sku' => 'CK95RGB-007',
                'price' => 199.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 150,
                'min_quantity' => 1,
                'weight' => 1.20,
                'dimensions' => '444 x 166 x 36 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/61141h-yvFL._AC_SX522_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/61ZrK+AniiL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/6119hM9xQWL._AC_SX522_.jpg"]',
                'meta_title' => 'Corsair K95 RGB Platinum XT - RGB Mechanical Keyboard',
                'meta_description' => 'The Corsair K95 RGB Platinum XT is a high-performance mechanical keyboard with customizable RGB lighting and programmable macro keys.',
                'rating_average' => 4.8,
                'rating_count' => 700,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Product 60
            [
                'category_id' => 8,
                'subcategory_id' => 10,
                'name' => 'Razer DeathAdder V2 Gaming Mouse',
                'slug' => 'razer-deathadder-v2-gaming-mouse',
                'description' => 'The Razer DeathAdder V2 Gaming Mouse features Razer Optical Mouse Switches, 20,000 DPI optical sensor, and customizable RGB Chroma backlighting.',
                'short_description' => 'High-precision gaming mouse with 20,000 DPI and Razer Optical Mouse Switches.',
                'sku' => 'RDV2GM-008',
                'price' => 69.99,
                'sale_price' => null,
                'cost_price' => null,
                'stock_quantity' => 200,
                'min_quantity' => 1,
                'weight' => 0.08,
                'dimensions' => '127 x 68 x 43 mm',
                'is_active' => true,
                'is_featured' => false,
                'manage_stock' => true,
                'stock_status' => 'in_stock',
                'image' => 'https://m.media-amazon.com/images/I/41iLtLRTsZL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'gallery' => '["https://m.media-amazon.com/images/I/41KiSTQ1ITL._AC_SX522_.jpg", "https://m.media-amazon.com/images/I/41CChwuSmXL._AC_SX522_.jpg", "image3.jpg"]',
                'meta_title' => 'Razer DeathAdder V2 - Precision Gaming Mouse',
                'meta_description' => 'The Razer DeathAdder V2 offers ultra-fast response time and high precision with a 20,000 DPI optical sensor, ideal for competitive gaming.',
                'rating_average' => 4.9,
                'rating_count' => 1500,
                'created_at' => now(),
                'updated_at' => now(),
            ],



        ]);
    }
}
